import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    // 'intro',
    // 'hello',
    {
      type: 'category',
      label: 'Android',
      items: ['android/intro'],
    },
    {
      type: 'category',
      label: 'Backend',
      items: [
        'backend/nl-service-level-description',
        'backend/nl-apis-documentation', 
        'backend/kong-gateway-integration', 
        'backend/student-and-spot-assessment-data', 
        'backend/assessment-cycle-management',
        {
          type: 'category',
          label: 'Scripts',
          items: [
            'backend/scripts/student-bulk-update',
            'backend/scripts/cwsn-students-ingestion',
            'backend/scripts/mentor-ingestion',
            'backend/scripts/bulk-examiner-ingestion',
            'backend/scripts/materialized-view-refresh',
            'backend/scripts/db-backup-script',
            'backend/scripts/db-backup-restore',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Devops',
      items: ['devops/intro'],
    }
  ]
};

export default sidebars;
