import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    // 'hello',
    {
      type: 'category',
      label: 'Android',
      items: ['android/intro'],
    },
    {
      type: 'category',
      label: 'Backend',
      items: ['backend/intro', 'backend/NL-APIs-Documentation', 'backend/Student-and-Spot-Assessment-Data', 'backend/Assessment-Cycle-Management', 'backend/Bulk-Examiner-Ingestion'],
    },
    {
      type: 'category',
      label: 'Devops',
      items: ['devops/intro'],
    }
  ]
};

export default sidebars;
